[versions]
android-gradle-plugin = "8.1.1"
kotlin = "1.9.10"
appcompat = "1.6.1"
material = "1.9.0"
lifecycle = "2.6.1"
recyclerView = "1.3.1"
constraintLayout = "2.1.4"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-std-lib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
recycler-view = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }

[bundles]
sample = ["kotlin-std-lib", "appcompat", "material", "constraint-layout"]
library = ["kotlin-std-lib", "lifecycle-common-java8", "recycler-view", "constraint-layout"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }